runtime: php
env: flex

runtime_config:
  document_root: .

#handlers:

#- url: /.*
  #script: auto

env_variables:
  APP_LOG: errorlog
  APP_KEY: app-key

  DB_CONNECTION: mysql
  DB_HOST: localhost;unix_socket=/cloudsql/sampleappgcp:us-central1:coffeeshop
  DB_DATABASE: inject_demodb
  DB_USERNAME: sql_injection
  DB_PASSWORD: foobar

beta_settings:
  cloud_sql_instances: sampleappgcp:us-central1:coffeeshop
